name: CI

on:
  push:
    branches: [ master, github_actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11 and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'maven'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Cucumber Tests
        run: mvn test -Dcucumber.options="--plugin json:target/cucumber-report.json --plugin html:target/cucumber-html-report.html"

      - name: Upload Cucumber JSON Report
        uses: actions/upload-artifact@v3  # Update to v3
        with:
          name: cucumber-json-report
          path: target/cucumber-report.json

      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v3  # Update to v3
        with:
          name: cucumber-html-report
          path: target/cucumber-html-report.html